"""Initial migration

Revision ID: 49caf406f31e
Revises: 
Create Date: 2025-08-03 20:26:54.975480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49caf406f31e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('roaster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=False),
    sa.Column('website', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('website')
    )
    op.create_table('bean',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('roast_level', sa.String(length=150), nullable=False),
    sa.Column('origin', sa.String(length=150), nullable=False),
    sa.Column('price_per_100_grams', sa.Float(), nullable=False),
    sa.Column('roaster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['roaster_id'], ['roaster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_bean',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bean_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bean_id'], ['bean.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'bean_id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bean_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=150), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('brew_method', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['bean_id'], ['bean.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('like',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('review_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    op.drop_table('review')
    op.drop_table('favorite_bean')
    op.drop_table('bean')
    op.drop_table('roaster')
    op.drop_table('app_user')
    # ### end Alembic commands ###
